[package]
name = "ensign"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "the ensign client"
publish = false

[[bin]]
name = "ensign"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
plumb = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }
