import { init } from "@perish/sealkit/init";

await init({
  tools: [
    "git",
    "deno",
    "cargo",
    "runseal",
    "ectropy",
    "plumb",
    "sh",
    "bash",
    "sed",
    "grep",
    "docker",
    "pnpm",
    "helm",
    "node",
  ],
  paths: [
    "Cargo.toml",
    "Cargo.lock",
    "biome.json",
    "ectropy.toml",
    "docs/vocabulary.md",
    "runseal.toml",
    "keel.toml",
    "AGENTS.md",
    "README.md",
    "package.json",
    "pnpm-workspace.yaml",
    "pnpm-lock.yaml",
    "apps/web/package.json",
    "apps/web/vite.config.ts",
    "sidecar.toml",
    "charts/ensign/Chart.yaml",
    ".runseal/deno.json",
    ".runseal/deno.lock",
    ".runseal/hooks/pre-commit",
    ".runseal/hooks/commit-msg",
    ".runseal/wrappers/guard.ts",
    ".runseal/wrappers/init.ts",
    ".runseal/wrappers/land.ts",
    ".forgejo/workflows/guard.yml",
  ],
});
